---
username: kwamedat
composer_home_owner: kwamedat
composer_home_group: kwamedat

dotfiles_repo: "https://github.com/kwame-dat/dotfiles.git"
dotfiles_repo_version: main
dotfiles_repo_local_destination: "~/Repo/2Areas/dotfiles"

dotfiles_files:
  - .Xresources
  - .Xresources-dpi
  - .aliases
  - .bashrc
  - .bin
  - .ca-bundle.crt
  - .functions
  - .gitconfig
  - .gitignore
  - .gitignore_global
  - .mbsyncrc
  - .mpd
  - .php-cs-fixer
  - .tmux.conf
  - .xbindkeysrc
  - .xmobarrc
  - .xmonad
  - .zshrc
  - .config

homebrew_installed_packages:
  - composer
  - fd
  - cmake
  - global
  - glslang
  - sbcl
  - node
  - ledger
  - mu
  - pandoc
  - pass
  - ripgrep
  - wget
  - aspell
  - coreutils
  - editorconfig
  - fzf
  - git
  - gnu-tar
  - go
  - libvterm
  - markdown
  - nvm
  - readline
  - sqlite
  - awscli
  - isync
  - browserpass
  - roots/tap/trellis-cli

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - amar1729/formulae

homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - alfred
  - appcleaner
  - audacity
  - alacritty
  - balenaetcher
  - calibre
  - discord
  - diskmaker-x
  - docker
  - emacs
  - gimp
  - google-chrome
  - lastpass
  - logitech-options
  - meld
  - microsoft-remote-desktop
  - mixxx
  - nextcloud
  - obs
  - querious
  - qutebrowser
  - skype
  - slack
  - spectacle
  - tableplus
  - tidal
  - visual-studio-code
  - vlc
  - whatsapp
  - zoom
  - font-inconsolata
  - font-cantarell
  - mactex
  - vagrant
  - parallels
  - stoplight-studio
  - insomnia
  - screaming-frog-seo-spider
  # - teamviewer
