---
username: kwamedat
composer_home_owner: kwamedat
composer_home_group: kwamedat

dotfiles_repo: "https://github.com/kwame-dat/dotfiles.git"
dotfiles_repo_version: master
dotfiles_repo_local_destination: "~/Repo/2Areas/dotfiles"

dotfiles_files:
  - .Xresources
  - .Xresources-dpi
  - .aliases
  - .bashrc
  - .ca-bundle.crt
  - .functions
  - .gitconfig
  - .gitignore
  - .gitignore_global
  - .mbsyncrc
  - .php-cs-fixer
  - .tmux.conf
  - .xbindkeysrc
  - .xmobarrc
  - .xmonad
  - .zshrc
  - .bin
  - .config
  - .mpd

homebrew_installed_packages:
  - ag
  - aspell
  - composer
  - coreutils
  - editorconfig
  - fd
  - git
  - global
  - glslang
  - gnu-tar
  - go
  - httpie
  - lastpass-cli
  - ledger
  - libvterm
  - markdown
  - mu
  - node
  - nvm
  - pandoc
  - pass
  - readline
  - ripgrep
  - sbcl
  - shellcheck
  - sqlite
  - wget

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - alfred
  - appcleaner
  - dbeaver-community
  - docker
  - emacs
  - google-chrome
  - hyper
  - mactex
  - sequel-pro
  - skype
  - slack
  - spectacle
  - vagrant
  - virtualbox
  - whatsapp
  - meld
