---
username: kwamedat
composer_home_owner: kwamedat
composer_home_group: kwamedat

dotfiles_repo: "https://github.com/kwame-dat/dotfiles.git"
dotfiles_repo_version: main
dotfiles_repo_local_destination: "~/Repo/2Areas/dotfiles"

dotfiles_files:
  - .Xresources
  - .Xresources-dpi
  - .aliases
  - .bashrc
  - .bin
  - .ca-bundle.crt
  - .config/alacritty
  - .config/polybar
  - .config/qutebrowser
  - .config/rofi
  - .config/surfraw
  - .config/sway
  - .config/systemd
  - .config/waybar
  - .functions
  - .gitconfig
  - .gitignore
  - .gitignore_global
  - .mbsyncrc
  - .mpd
  - .php-cs-fixer
  - .tmux.conf
  - .xbindkeysrc
  - .xmobarrc
  - .xmonad
  - .zshrc

homebrew_installed_packages:
  # - composer
  # - fd
  # - global
  # - glslang
  # - ledger
  # - mu
  # - node
  # - pandoc
  # - pass
  # - ripgrep
  # - sbcl
  # - wget
  - aspell
  - coreutils
  - editorconfig
  - fzf
  - git
  - gnu-tar
  - go
  - libvterm
  - markdown
  - nvm
  - readline
  - sqlite

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers

homebrew_cask_appdir: /Applications

homebrew_cask_apps:
  - alfred
  - appcleaner
  - audacity
  - balenaetcher
  - calibre
  - dbeaver-community
  - discord
  - diskmaker-x
  - docker
  - dropbox
  - emacs
  - gimp
  - google-chrome
  - lastpass
  - logitech-options
  - mactex
  - meld
  - microsoft-remote-desktop
  - mixxx
  - nextcloud
  - obs
  - querious
  - qutebrowser
  - sequel-pro
  - skype
  - slack
  - spectacle
  - sublime-text
  - teamviewer
  - tidal
  # - vagrant
  - visual-studio-code
  - vlc
  - whatsapp
  - xbox360-controller-driver-unofficial
  - zoom
