---
- hosts: all
  connection: local
  vars_files:
    - config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - {role: geerlingguy.mac.homebrew, tags: [homebrew]}
    - {role: user-configuration, tags: [user-configuration]}
