---
- hosts: all
  connection: local
  become: true
  vars_files:
    - config.yml

  roles:
    - {role: user-configuration, tags: [user-configuration]}
    - {role: docker, tags: [docker]}
    - {role: general-apps, tags: [general-apps]}
    - {role: emacs, tags: [emacs, emacs-packages]}
    - {role: php, tags: [php]}
    - {role: window-manager, tags: [window-manager]}
