---
- hosts: all
  connection: local
  become: true
  vars_files:
    - config.yml

  roles:
    - { role: user-configuration, tags: [user-configuration] }
    - { role: php, tags: [php] }
    - { role: composer, tags: [composer] }
    - { role: emacs, tags: [emacs, emacs-packages] }

