---
- name: Include distribution and version-specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
      skip: true

- name: Install Emacs
  package:
    name: emacs
    state: present

- name: Install Emacs Packages
  package:
    name: "{{ item.name }}"
    state: "{{ item.state}}"
  with_items: "{{ emacs_packages }}"

# Configure Emacs Dot File.
# - include_tasks: configure-dotfile.yml
