---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure PHP packages are installed.
  apt:
    name: "{{ php_packages + php_packages_extra }}"
    state: "{{ php_packages_state }}"
    install_recommends: "{{ php_install_recommends }}"
  register: php_package_install
  notify: restart webserver
