---
- name: User Configuration - Add sudoers entry for "{{ username }}"
  become: true
  lineinfile:
    path: "/etc/sudoers.d/{{ username }}"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    create: true
    mode: "0640"
